name: Deploy to Xserver

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Xserver via FTP
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: sv15107.xserver.jp
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: './'
        remoteDir: '/web-manato.com/public_html/portfolio.web-manato.com/demo/docs'
        exclude: |
          README.md
          README.txt
          .github/
          .git/
          .gitignore
          .gitattributes
          node_modules/
          package.json
          package-lock.json
          yarn.lock
          .env
          .env.local
          .env.example
          *.log
          .DS_Store
          Thumbs.db